appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: MEe7TJdQkWv0e6ft6JYTLQAZv2sAz67T47zntiyeqtjt2Pm8JOhANwBHFRI6l1Ko21ZY9PcxrVVChoeWK+/8sp1ai1YB8HeQjU4/HIboGkeQJ4QCBioFU+NMRBpQt0B+tPQRIKtNZw3ydX/qYlwL5FZI6akSS7LFj2WOHdzw2Mz5ZLk8e3zEPoHtq/whe5tmMj4i6pFtnKMW0VSfS7ciw36Wk0nSAHQoFaOez+jAzs5Z6eqEH7THUO9pFZM24t25zWSbJOHfuvIaM4DYZttX9Db0ogU8OqY3ok1oRmSxlDQ85aT2uyNQVHgD9VcimMVkc5hG41tNl6cvUptY3rHHJUSVXEp9N4nQaYSYWawys7mwu1PwaYqL/BHVqOMWXNbCsF18rl97nsLEDhzcrLpO5g5qz7+IOMVfca5qpnRgwp8LYc0hCNQJPT+enZz6QRYRa2HarhLnyrE5l/4CHXhIDNjbzOulLf6CumX4kwYlNzbkQlBq3Df8RVzTURv/bAFh+uu1kqLyK/IftEDfCTtSCYIGTNDz+JOn+DeK9S5Wuq0DMw8x5FfjowXhiO+MCYogvE/kFFo7pXI6vf0Ynd69RXkSRNJaBTAgqCDCPGlfF+HNwIBB34Au+dIk21CTTWJC1xwjsvARQFYteBEG2HuL2ZgGyY8NHeRY6UVEirlznSM=
conda_forge_output_validation: true
